---
name: Lint

on:
  push:
    branches: ["main", "develop", "v2.0"]
  pull_request:
    branches: ["main", "develop", "v2.0"]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[lint]"
      - name: Analyze code with pycodestyle
        run: python -m pycodestyle ahttp_client --max-line-length=120
      - name: Check formatting with Black
        run: python -m black --check ahttp_client example
